### ISSUE TITLE
ipv6addr: unrecognized option '---no-prefixlength'

### ISSUE THREAD

**Issue by Malvineous** [pbiering/ipv6calc#14]
According to the docs I can do this:
```
$ ipv6calc --out ipv6 --examples
  --forceprefix <num>: Force prefix to <num>
  --no-prefixlength: Don't print prefix length if given on input
```
However those two options don't seem to work:
```
$ ipv6calc --in prefix+mac "1:2:3:4::/56" "11:22:33:44:55:66" --action prefixmac2ipv6 --out ipv6addr --no-prefixlength
ipv6calc: unrecognized option '--no-prefixlength'
```
```
$ ipv6calc --in prefix+mac "1:2:3:4::" "11:22:33:44:55:66" --action prefixmac2ipv6 --out ipv6addr --force-prefix 56
ipv6calc: unrecognized option '--force-prefix'
```
The other options listed in `--examples` work.

**Comment by pbiering** [comment]
Thank you for bringing this to my attention, looks like I forgot to implement this fully...
- "force-prefix": was implemented, but forgotten to catch the option
- "no-prefixlength": totally forgotten

Fixed in by https://github.com/pbiering/ipv6calc/commit/c25613c3ce12e40c8190741a17a899af47ae8430

Will create a release next
